stages:
  - detect
  - build
  - installer
  - release

include:
  - local: '.gitlab-ci/nightly-app.yml'
  - local: '.gitlab-ci/release-app.yml'
  - local: '.gitlab-ci/release-core.yml'
  - local: '.gitlab-ci/release-tool.yml'
