; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

; 环境变量配置说明：
;   KAEPHI_VERSION     - 应用版本号（必需），例如 "0.5.0" 或 "0.5.0+abc123def456..."
;                        建议使用完整 commit hash 以保持与软件内部展示一致
;   KAEPHI_PROJECT_DIR - 项目根目录（可选），用于定位 LICENSE、README 等文件，默认为脚本所在目录
;   KAEPHI_PUBLISH_DIR - 发布输出目录（必需），包含编译产物的目录

#define MyAppName "KaedePhi"
#define MyAppPublisher "NuanR_Star Ciallo Team"
#define MyAppURL "https://www.nuanr-mxi.com"
#define MyAppExeName "KaedePhi.Tool.App.exe"

; 从环境变量获取版本号，如果未设置则报错
#define MyAppVersion GetEnv("KAEPHI_VERSION")
#if MyAppVersion == ""
  #error "环境变量 KAEPHI_VERSION 未设置，请设置版本号，例如 set KAEPHI_VERSION=0.5.0"
#endif

; 从环境变量获取项目根目录，默认为脚本所在目录
#define ProjectDir GetEnv("KAEPHI_PROJECT_DIR")
#if ProjectDir == ""
  #define ProjectDir "."
#endif

; 从环境变量获取发布目录
#define PublishDir GetEnv("KAEPHI_PUBLISH_DIR")
#if PublishDir == ""
  #error "环境变量 KAEPHI_PUBLISH_DIR 未设置，请设置发布输出目录"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{CE5E9518-27D0-44CC-925F-DDBAD2355D52}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
; 显示名称仅保留程序名，版本与 commit hash 只保存在版本字段中
AppVerName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile={#ProjectDir}\LICENSE
InfoBeforeFile={#ProjectDir}\README.md
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir={#ProjectDir}\setup
OutputBaseFilename=KaedePhi-{#MyAppVersion}
SetupIconFile={#ProjectDir}\KaedePhiIcon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#PublishDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#PublishDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
var
  DeleteUserData: Boolean;

// 安装前清空目标目录，避免旧版本残留文件影响升级
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
  begin
    // 先移除旧卸载器，再删除目录中全部旧文件
    DelTree(ExpandConstant('{uninstallexe}'), True, True, False);
    DelTree(ExpandConstant('{app}'), False, True, True);
  end;
end;

function InitializeUninstall(): Boolean;
begin
  Result := True;
  DeleteUserData := False;
  if MsgBox('是否同时删除 KaedePhi 的所有用户数据（配置、日志、工作区）？',
    mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES then
    DeleteUserData := True;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin
    if DeleteUserData then
      DelTree(ExpandConstant('{localappdata}\KaedePhi'), True, True, True);
  end;
end;

