//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaedePhi.Core.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaedePhi.Core.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建缓动对象时，缓动编号必须位于该格式定义的有效范围内。.
        /// </summary>
        internal static string kpce_0001_description {
            get {
                return ResourceManager.GetString("kpce_0001_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缓动编号 {0} 超出 {1} 格式的有效范围 [{2}, {3}].
        /// </summary>
        internal static string kpce_0001_message_format {
            get {
                return ResourceManager.GetString("kpce_0001_message_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缓动编号超出格式有效范围.
        /// </summary>
        internal static string kpce_0001_title {
            get {
                return ResourceManager.GetString("kpce_0001_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new Beat(int[]) 的数组长度不是 3，运行时必然抛出 ArgumentException。.
        /// </summary>
        internal static string kpce_0002_description {
            get {
                return ResourceManager.GetString("kpce_0002_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat 数组必须恰好包含 3 个元素（整数部分、分子、分母），当前长度为 {0}。.
        /// </summary>
        internal static string kpce_0002_message_format {
            get {
                return ResourceManager.GetString("kpce_0002_message_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat 数组长度不是 3.
        /// </summary>
        internal static string kpce_0002_title {
            get {
                return ResourceManager.GetString("kpce_0002_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat 分母为零在运行时必然抛出 ArgumentException。.
        /// </summary>
        internal static string kpce_0003_description {
            get {
                return ResourceManager.GetString("kpce_0003_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat 数组的分母（下标 2）不能为 0。.
        /// </summary>
        internal static string kpce_0003_message_format {
            get {
                return ResourceManager.GetString("kpce_0003_message_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat 分母为零.
        /// </summary>
        internal static string kpce_0003_title {
            get {
                return ResourceManager.GetString("kpce_0003_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat 分母为负在运行时必然抛出 ArgumentException。.
        /// </summary>
        internal static string kpce_0004_description {
            get {
                return ResourceManager.GetString("kpce_0004_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat 数组的分母（下标 2）必须为正数，当前为 {0}。.
        /// </summary>
        internal static string kpce_0004_message_format {
            get {
                return ResourceManager.GetString("kpce_0004_message_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat 分母为负数.
        /// </summary>
        internal static string kpce_0004_title {
            get {
                return ResourceManager.GetString("kpce_0004_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new Beat(double) 传入 NaN 或无穷大在运行时必然抛出 ArgumentOutOfRangeException。.
        /// </summary>
        internal static string kpce_0005_description {
            get {
                return ResourceManager.GetString("kpce_0005_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat 构造参数必须是有限数值，不能为 NaN 或无穷大。.
        /// </summary>
        internal static string kpce_0005_message_format {
            get {
                return ResourceManager.GetString("kpce_0005_message_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat 数值必须有限.
        /// </summary>
        internal static string kpce_0005_title {
            get {
                return ResourceManager.GetString("kpce_0005_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalNumberOfNotes 的值遵循 RePhiEdit 规范（包含 FakeNote、不包含 Hold），与 Notes 的真实数量不一致。.
        /// </summary>
        internal static string kpcr_0006_description {
            get {
                return ResourceManager.GetString("kpcr_0006_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 除非你知道你在做什么，否则不要访问 TotalNumberOfNotes：该值严格按 RePhiEdit 规范计算（包含 FakeNote、不包含 Hold），不能反映 Note 的真实数量。请按你自己的规则从 JudgeLine.Notes 中计算音符数量。.
        /// </summary>
        internal static string kpcr_0006_message_format {
            get {
                return ResourceManager.GetString("kpcr_0006_message_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不应访问 TotalNumberOfNotes.
        /// </summary>
        internal static string kpcr_0006_title {
            get {
                return ResourceManager.GetString("kpcr_0006_title", resourceCulture);
            }
        }
    }
}
