//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaedePhi.Tool.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaedePhi.Tool.Analyzers.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将容差参数除以 100.
        /// </summary>
        internal static string kpte_0001_code_fix_title {
            get {
                return ResourceManager.GetString("kpte_0001_code_fix_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容差参数使用百分比表示，值大于或等于 100 会导致父线解绑结果难以预期。.
        /// </summary>
        internal static string kpte_0001_description {
            get {
                return ResourceManager.GetString("kpte_0001_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容差参数使用百分比表示，值 {0} 过大，是否指的是 {0} / 100？.
        /// </summary>
        internal static string kpte_0001_message_format {
            get {
                return ResourceManager.GetString("kpte_0001_message_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容差参数可能过大.
        /// </summary>
        internal static string kpte_0001_title {
            get {
                return ResourceManager.GetString("kpte_0001_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将 cutLength 改为倒数.
        /// </summary>
        internal static string kpti_0001_code_fix_title {
            get {
                return ResourceManager.GetString("kpti_0001_code_fix_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 传递给 CutEventToLinear/CutEventsInRange 的 cutLength 参数大于 1，可能是忘记做倒数运算。.
        /// </summary>
        internal static string kpti_0001_description {
            get {
                return ResourceManager.GetString("kpti_0001_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此值通常不大于 1，您是否指的是 1 / {0}？.
        /// </summary>
        internal static string kpti_0001_message_format {
            get {
                return ResourceManager.GetString("kpti_0001_message_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cutLength 参数可能过大.
        /// </summary>
        internal static string kpti_0001_title {
            get {
                return ResourceManager.GetString("kpti_0001_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 传递给 CutEventToLinear/CutEventsInRange 的 cutLength 参数等于 1，可能不是预期的切割长度。.
        /// </summary>
        internal static string kpti_0002_description {
            get {
                return ResourceManager.GetString("kpti_0002_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此值通常不等于1，您是否指小数或某值的倒数？.
        /// </summary>
        internal static string kpti_0002_message_format {
            get {
                return ResourceManager.GetString("kpti_0002_message_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cutLength 参数可能不正确.
        /// </summary>
        internal static string kpti_0002_title {
            get {
                return ResourceManager.GetString("kpti_0002_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将容差参数乘以 100.
        /// </summary>
        internal static string kpti_0003_code_fix_title {
            get {
                return ResourceManager.GetString("kpti_0003_code_fix_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容差参数使用百分比表示，小于 0.01 的值可能生成大量事件并消耗过多内存。.
        /// </summary>
        internal static string kpti_0003_description {
            get {
                return ResourceManager.GetString("kpti_0003_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容差参数使用百分比表示，值 {0} 过小，可能导致最终结果大量消耗内存；是否指的是 {0} * 100？.
        /// </summary>
        internal static string kpti_0003_message_format {
            get {
                return ResourceManager.GetString("kpti_0003_message_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容差参数可能过小.
        /// </summary>
        internal static string kpti_0003_title {
            get {
                return ResourceManager.GetString("kpti_0003_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改用普通 FatherUnbind 解绑器.
        /// </summary>
        internal static string kptr_0001_code_fix_title {
            get {
                return ResourceManager.GetString("kptr_0001_code_fix_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自适应采样的 tolerance 为 0 可能产生额外性能开销；如需禁用容差行为，应调用不包含容差参数的普通解绑器。.
        /// </summary>
        internal static string kptr_0001_description {
            get {
                return ResourceManager.GetString("kptr_0001_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自适应采样的 tolerance 为 0，可能导致额外性能开销；如果想禁用容差行为，是否改用普通解绑器？.
        /// </summary>
        internal static string kptr_0001_message_format {
            get {
                return ResourceManager.GetString("kptr_0001_message_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动态解绑可能浪费性能.
        /// </summary>
        internal static string kptr_0001_title {
            get {
                return ResourceManager.GetString("kptr_0001_title", resourceCulture);
            }
        }
    }
}
