<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;PreRelease</Configurations>
    <Platforms>x64</Platforms>
    <AssemblyName>KaedePhi.Tool</AssemblyName>
    <RootNamespace>KaedePhi.Tool</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KaedePhi.Core\KaedePhi.Core.csproj" />
    <ProjectReference
      Include="..\KaedePhi.Tool.Analyzers\KaedePhi.Tool.Analyzers\KaedePhi.Tool.Analyzers.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
    <ProjectReference
      Include="..\KaedePhi.Core.Analyzers\KaedePhi.Core.Analyzers\KaedePhi.Core.Analyzers.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference Include="SkiaSharp" Version="4.148.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.148.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.148.0" />
  </ItemGroup>
</Project>
