//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaedePhi.Tool.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CliLocalizationString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CliLocalizationString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaedePhi.Tool.Localization.CliLocalizationString", typeof(CliLocalizationString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 臀饭制工具集.
        /// </summary>
        public static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换输入谱面到目标谱面格式.
        /// </summary>
        public static string convert_command_desc {
            get {
                return ResourceManager.GetString("convert_command_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标格式（如：RePhiEdit、PhiEdit、PhigrosV3）.
        /// </summary>
        public static string convert_command_opt_target {
            get {
                return ResourceManager.GetString("convert_command_opt_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 咦？是写错命令了吗？.
        /// </summary>
        public static string err_unknown {
            get {
                return ResourceManager.GetString("err_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拟合谱面中线性事件.
        /// </summary>
        public static string fit_command_desc {
            get {
                return ResourceManager.GetString("fit_command_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将谱面各通道事件渲染为 PNG 图片.
        /// </summary>
        public static string render_command_desc {
            get {
                return ResourceManager.GetString("render_command_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法加载谱面，清检查文件格式。.
        /// </summary>
        public static string render_err_load_failed {
            get {
                return ResourceManager.GetString("render_err_load_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渲染时发生错误：{0}.
        /// </summary>
        public static string render_err_render_failed {
            get {
                return ResourceManager.GetString("render_err_render_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渲染完成，共写入 {0} 张图片到 {1}.
        /// </summary>
        public static string render_msg_done {
            get {
                return ResourceManager.GetString("render_msg_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始渲染，输出目录：{0}.
        /// </summary>
        public static string render_msg_start {
            get {
                return ResourceManager.GetString("render_msg_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每拍格线细分数（1=只绘节拍线，4=绘四分音符线，默认 2）.
        /// </summary>
        public static string render_opt_beat_subdivisions {
            get {
                return ResourceManager.GetString("render_opt_beat_subdivisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每个通道的宽度（像素，默认：150）.
        /// </summary>
        public static string render_opt_channel_width {
            get {
                return ResourceManager.GetString("render_opt_channel_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只渲染指定索引的事件层（需同时指定 --line）.
        /// </summary>
        public static string render_opt_layer {
            get {
                return ResourceManager.GetString("render_opt_layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只渲染指定索引的判定线（不指定则渲染全部）.
        /// </summary>
        public static string render_opt_line {
            get {
                return ResourceManager.GetString("render_opt_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片输出文件夹路径。.
        /// </summary>
        public static string render_opt_output {
            get {
                return ResourceManager.GetString("render_opt_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每拍对应的像素高度（默认：100）.
        /// </summary>
        public static string render_opt_pixels_per_beat {
            get {
                return ResourceManager.GetString("render_opt_pixels_per_beat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每个事件的曲线采样点数（默认：64）.
        /// </summary>
        public static string render_opt_samples {
            get {
                return ResourceManager.GetString("render_opt_samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有找到可渲染的事件层，请检查输入谱面或 --line / --layer 参数。.
        /// </summary>
        public static string render_warn_nothing {
            get {
                return ResourceManager.GetString("render_warn_nothing", resourceCulture);
            }
        }
    }
}
