//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaedePhi.Tool.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CliLocalizationString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CliLocalizationString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaedePhi.Tool.Localization.CliLocalizationString", typeof(CliLocalizationString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KaedePhi - 简单易用万能的Phigros社区谱面工具集.
        /// </summary>
        public static string app_description {
            get {
                return ResourceManager.GetString("app_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KaedePhi.
        /// </summary>
        public static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置管理.
        /// </summary>
        public static string branch_config_desc {
            get {
                return ResourceManager.GetString("branch_config_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区管理.
        /// </summary>
        public static string branch_workspace_desc {
            get {
                return ResourceManager.GetString("branch_workspace_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧版行为模式，这个模式通常会消耗更多性能，但是输出通常更加稳定.
        /// </summary>
        public static string cli_opt_classic_mode_desc {
            get {
                return ResourceManager.GetString("cli_opt_classic_mode_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用压缩.
        /// </summary>
        public static string cli_opt_compress_desc {
            get {
                return ResourceManager.GetString("cli_opt_compress_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试运行模式，不写入文件.
        /// </summary>
        public static string cli_opt_dry_run_desc {
            get {
                return ResourceManager.GetString("cli_opt_dry_run_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使输出的文件格式化.
        /// </summary>
        public static string cli_opt_format_desc {
            get {
                return ResourceManager.GetString("cli_opt_format_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入的 RPE/PhiEdit 谱面文件路径.
        /// </summary>
        public static string cli_opt_input_phiedit_desc {
            get {
                return ResourceManager.GetString("cli_opt_input_phiedit_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入的 RPE 谱面文件路径（与 --workspace 二选一）.
        /// </summary>
        public static string cli_opt_input_rpe_desc {
            get {
                return ResourceManager.GetString("cli_opt_input_rpe_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出文件路径（不填则自动生成 _KaedePhi 后缀）.
        /// </summary>
        public static string cli_opt_output_auto_desc {
            get {
                return ResourceManager.GetString("cli_opt_output_auto_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出文件路径.
        /// </summary>
        public static string cli_opt_output_path_desc {
            get {
                return ResourceManager.GetString("cli_opt_output_path_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采样精度（每拍细分数，默认：64，即每次采样步进64/1拍）.
        /// </summary>
        public static string cli_opt_precision_desc {
            get {
                return ResourceManager.GetString("cli_opt_precision_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流式输出模式（若发生内存不足错误，请考虑使用此选项）.
        /// </summary>
        public static string cli_opt_stream_output_desc {
            get {
                return ResourceManager.GetString("cli_opt_stream_output_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拟合容差百分比（默认：5%）.
        /// </summary>
        public static string cli_opt_tolerance_desc {
            get {
                return ResourceManager.GetString("cli_opt_tolerance_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只清理指定工作区（不填则清理全部）.
        /// </summary>
        public static string cli_opt_workspace_clear_id_desc {
            get {
                return ResourceManager.GetString("cli_opt_workspace_clear_id_desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 明确确认清理全部工作区.
        /// </summary>
        public static string cli_opt_workspace_clear_all_desc {
            get {
                return ResourceManager.GetString("cli_opt_workspace_clear_all_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区 ID（默认：default）.
        /// </summary>
        public static string cli_opt_workspace_default_desc {
            get {
                return ResourceManager.GetString("cli_opt_workspace_default_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区 ID（与 --input 二选一）.
        /// </summary>
        public static string cli_opt_workspace_rpe_desc {
            get {
                return ResourceManager.GetString("cli_opt_workspace_rpe_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置配置文件为默认值.
        /// </summary>
        public static string cmd_config_reset_desc {
            get {
                return ResourceManager.GetString("cmd_config_reset_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将谱面转换为其他格式（尚未完整实现）.
        /// </summary>
        public static string cmd_convert_desc {
            get {
                return ResourceManager.GetString("cmd_convert_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 砍碎所有事件为线性事件.
        /// </summary>
        public static string cmd_cut_event_desc {
            get {
                return ResourceManager.GetString("cmd_cut_event_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将所有判定线的多个事件层级合并为单一层级.
        /// </summary>
        public static string cmd_layer_merge_desc {
            get {
                return ResourceManager.GetString("cmd_layer_merge_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入谱面文件到工作区，供后续操作使用.
        /// </summary>
        public static string cmd_load_desc {
            get {
                return ResourceManager.GetString("cmd_load_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将工作区中的谱面保存到文件.
        /// </summary>
        public static string cmd_save_desc {
            get {
                return ResourceManager.GetString("cmd_save_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将判定线与父级解绑.
        /// </summary>
        public static string cmd_unbind_father_desc {
            get {
                return ResourceManager.GetString("cmd_unbind_father_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示当前版本号.
        /// </summary>
        public static string cmd_version_desc {
            get {
                return ResourceManager.GetString("cmd_version_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清理工作区缓存（可指定 --id 只清理单个）.
        /// </summary>
        public static string cmd_workspace_clear_desc {
            get {
                return ResourceManager.GetString("cmd_workspace_clear_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列出所有工作区 ID.
        /// </summary>
        public static string cmd_workspace_list_desc {
            get {
                return ResourceManager.GetString("cmd_workspace_list_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换输入谱面到目标谱面格式.
        /// </summary>
        public static string convert_command_desc {
            get {
                return ResourceManager.GetString("convert_command_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标格式.
        /// </summary>
        public static string convert_command_opt_target {
            get {
                return ResourceManager.GetString("convert_command_opt_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过滤假音符（删除假音符）.
        /// </summary>
        public static string convert_opt_filter_fake_notes {
            get {
                return ResourceManager.GetString("convert_opt_filter_fake_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用经典合并模式（固定采样）.
        /// </summary>
        public static string convert_opt_merge_classic {
            get {
                return ResourceManager.GetString("convert_opt_merge_classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多层级事件合并的精度.
        /// </summary>
        public static string convert_opt_merge_precision {
            get {
                return ResourceManager.GetString("convert_opt_merge_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多层级事件合并的容差百分比.
        /// </summary>
        public static string convert_opt_merge_tolerance {
            get {
                return ResourceManager.GetString("convert_opt_merge_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用负透明度段判定线抬高至屏幕外.
        /// </summary>
        public static string convert_opt_negative_alpha_elevation {
            get {
                return ResourceManager.GetString("convert_opt_negative_alpha_elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 负透明度段每次抬高的 KPC Y 偏移量（默认：4.0）.
        /// </summary>
        public static string convert_opt_negative_alpha_step {
            get {
                return ResourceManager.GetString("convert_opt_negative_alpha_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用合并后的自动压缩.
        /// </summary>
        public static string convert_opt_no_merge_compress {
            get {
                return ResourceManager.GetString("convert_opt_no_merge_compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用解绑后的自动压缩.
        /// </summary>
        public static string convert_opt_no_unbind_compress {
            get {
                return ResourceManager.GetString("convert_opt_no_unbind_compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE 输出时不透明度通道的切割精度.
        /// </summary>
        public static string convert_opt_pe_alpha_precision {
            get {
                return ResourceManager.GetString("convert_opt_pe_alpha_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE 输出时不透明度通道的压缩容差百分比.
        /// </summary>
        public static string convert_opt_pe_alpha_tolerance {
            get {
                return ResourceManager.GetString("convert_opt_pe_alpha_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE 不支持缓动类型的近似采样精度（每拍细分数）.
        /// </summary>
        public static string convert_opt_pe_easing_precision {
            get {
                return ResourceManager.GetString("convert_opt_pe_easing_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE 输出时速度通道的切割精度.
        /// </summary>
        public static string convert_opt_pe_speed_precision {
            get {
                return ResourceManager.GetString("convert_opt_pe_speed_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE 输出时速度通道的压缩容差百分比.
        /// </summary>
        public static string convert_opt_pe_speed_tolerance {
            get {
                return ResourceManager.GetString("convert_opt_pe_speed_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE 输出时帧结束后的尾部填充拍数（默认：1/64拍）.
        /// </summary>
        public static string convert_opt_pe_trailing_padding {
            get {
                return ResourceManager.GetString("convert_opt_pe_trailing_padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE 输出时未对齐的 X/Y 事件修正精度.
        /// </summary>
        public static string convert_opt_pe_xy_precision {
            get {
                return ResourceManager.GetString("convert_opt_pe_xy_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phigros 输出时不透明度通道的切割精度.
        /// </summary>
        public static string convert_opt_phigros_alpha_precision {
            get {
                return ResourceManager.GetString("convert_opt_phigros_alpha_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phigros 输出时不透明度通道的压缩容差百分比.
        /// </summary>
        public static string convert_opt_phigros_alpha_tolerance {
            get {
                return ResourceManager.GetString("convert_opt_phigros_alpha_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phigros 输出时的默认 BPM（用于变节拍谱面）.
        /// </summary>
        public static string convert_opt_phigros_bpm {
            get {
                return ResourceManager.GetString("convert_opt_phigros_bpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phigros 不支持缓动类型的近似采样精度.
        /// </summary>
        public static string convert_opt_phigros_easing_precision {
            get {
                return ResourceManager.GetString("convert_opt_phigros_easing_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phigros 输出时速度通道的切割精度.
        /// </summary>
        public static string convert_opt_phigros_speed_precision {
            get {
                return ResourceManager.GetString("convert_opt_phigros_speed_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phigros 输出时未对齐的 X/Y 事件修正精度.
        /// </summary>
        public static string convert_opt_phigros_xy_precision {
            get {
                return ResourceManager.GetString("convert_opt_phigros_xy_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除带有 AttachUi 的判定线.
        /// </summary>
        public static string convert_opt_remove_attach_ui {
            get {
                return ResourceManager.GetString("convert_opt_remove_attach_ui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除非默认纹理的判定线.
        /// </summary>
        public static string convert_opt_remove_texture {
            get {
                return ResourceManager.GetString("convert_opt_remove_texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用经典解绑模式（等间距采样）.
        /// </summary>
        public static string convert_opt_unbind_classic {
            get {
                return ResourceManager.GetString("convert_opt_unbind_classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父级解绑时的采样精度（数值越高越精细，不建议超过64）.
        /// </summary>
        public static string convert_opt_unbind_precision {
            get {
                return ResourceManager.GetString("convert_opt_unbind_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父级解绑时的容差百分比.
        /// </summary>
        public static string convert_opt_unbind_tolerance {
            get {
                return ResourceManager.GetString("convert_opt_unbind_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 某些选项禁用时，必须启用旧版行为.
        /// </summary>
        public static string err_classic_disablsed {
            get {
                return ResourceManager.GetString("err_classic_disablsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要提供 --input 哟，或者用 --workspace 也可以~.
        /// </summary>
        public static string err_input_required {
            get {
                return ResourceManager.GetString("err_input_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to --input 与 --workspace 不能同时指定。
        /// </summary>
        public static string err_input_workspace_conflict {
            get {
                return ResourceManager.GetString("err_input_workspace_conflict", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 输出路径不能覆盖输入谱面文件。
        /// </summary>
        public static string err_output_input_same {
            get {
                return ResourceManager.GetString("err_output_input_same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出的结果可能有些大哦~请试着添加&quot;--stream&quot;选项来减少内存占用！若这没有解决你的问题，请将以下信息发送到https://github.com/NuanRMxi-Lazy-Team/KaedePhi/issues，我们会尽快修复这个问题！
        ///{0}.
        /// </summary>
        public static string err_out_of_memory {
            get {
                return ResourceManager.GetString("err_out_of_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要提供 --output 才能帮你保存呢~.
        /// </summary>
        public static string err_output_required {
            get {
                return ResourceManager.GetString("err_output_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 操作已取消。
        /// </summary>
        public static string err_cancelled {
            get {
                return ResourceManager.GetString("err_cancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 请使用 --id 清理单个工作区，或使用 --all 明确确认清理全部工作区。
        /// </summary>
        public static string err_workspace_clear_selection {
            get {
                return ResourceManager.GetString("err_workspace_clear_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すみません！软件遇到了未知错误！请将以下信息发送到https://github.com/NuanRMxi-Lazy-Team/KaedePhi/issues 我们会尽快修复这个问题！
        ///{0}.
        /// </summary>
        public static string err_ukerr {
            get {
                return ResourceManager.GetString("err_ukerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这个命令功能还未完全实现呢....
        /// </summary>
        public static string err_unimplemented {
            get {
                return ResourceManager.GetString("err_unimplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 咦？是写错命令了吗？.
        /// </summary>
        public static string err_unknown {
            get {
                return ResourceManager.GetString("err_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区 ID 包含非法字符，只允许字母、数字、下划线和连字符。.
        /// </summary>
        public static string err_workspace_id_invalid_chars {
            get {
                return ResourceManager.GetString("err_workspace_id_invalid_chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区 ID 不能为空或空白。.
        /// </summary>
        public static string err_workspace_id_null {
            get {
                return ResourceManager.GetString("err_workspace_id_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区 ID 解析到工作区根目录以外的路径。.
        /// </summary>
        public static string err_workspace_id_path_traversal {
            get {
                return ResourceManager.GetString("err_workspace_id_path_traversal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有找到工作区 {0} 喵....
        /// </summary>
        public static string err_workspace_missing {
            get {
                return ResourceManager.GetString("err_workspace_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到工作区 &apos;{0}&apos;。.
        /// </summary>
        public static string err_workspace_not_found {
            get {
                return ResourceManager.GetString("err_workspace_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拟合谱面中线性事件.
        /// </summary>
        public static string fit_command_desc {
            get {
                return ResourceManager.GetString("fit_command_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以用 --help 查看所有可用命令哦~.
        /// </summary>
        public static string hint_use_help {
            get {
                return ResourceManager.GetString("hint_use_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 咦？是输错命令了吗？可以试试--help哦~.
        /// </summary>
        public static string hit_help {
            get {
                return ResourceManager.GetString("hit_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 哗啦啦~ 所有工作区都打扫干净了喵！.
        /// </summary>
        public static string msg_cleared {
            get {
                return ResourceManager.GetString("msg_cleared", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 工作区 {0} 已清理.
        /// </summary>
        public static string msg_workspace_cleared {
            get {
                return ResourceManager.GetString("msg_workspace_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置文件已重置为默认值：{0}.
        /// </summary>
        public static string msg_config_reset_done {
            get {
                return ResourceManager.GetString("msg_config_reset_done", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 配置文件保存失败，请检查权限或磁盘空间：{0}.
        /// </summary>
        public static string err_config_save_failed {
            get {
                return ResourceManager.GetString("err_config_save_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 还没想好怎么写喵...所以详见README.md喵....
        /// </summary>
        public static string msg_help {
            get {
                return ResourceManager.GetString("msg_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已经将文件送入 {0} 工作区啦！.
        /// </summary>
        public static string msg_workspace_loaded {
            get {
                return ResourceManager.GetString("msg_workspace_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 做好啦！把工作区 &apos;{0}&apos; 存到 &apos;{1}&apos; 了！.
        /// </summary>
        public static string msg_workspace_saved {
            get {
                return ResourceManager.GetString("msg_workspace_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件已经成功输出到 {0} 了！.
        /// </summary>
        public static string msg_written {
            get {
                return ResourceManager.GetString("msg_written", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/NuanRMxi-Lazy-Team/KaedePhi.
        /// </summary>
        public static string project_link {
            get {
                return ResourceManager.GetString("project_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将谱面各通道事件渲染为 PNG 图片.
        /// </summary>
        public static string render_command_desc {
            get {
                return ResourceManager.GetString("render_command_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法加载谱面，清检查文件格式。.
        /// </summary>
        public static string render_err_load_failed {
            get {
                return ResourceManager.GetString("render_err_load_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渲染时发生错误：{0}.
        /// </summary>
        public static string render_err_render_failed {
            get {
                return ResourceManager.GetString("render_err_render_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渲染完成，共写入 {0} 张图片到 {1}.
        /// </summary>
        public static string render_msg_done {
            get {
                return ResourceManager.GetString("render_msg_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始渲染，输出目录：{0}.
        /// </summary>
        public static string render_msg_start {
            get {
                return ResourceManager.GetString("render_msg_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每拍格线细分数（1=只绘节拍线，4=绘四分音符线，默认 2）.
        /// </summary>
        public static string render_opt_beat_subdivisions {
            get {
                return ResourceManager.GetString("render_opt_beat_subdivisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每个通道的宽度（像素，默认：150）.
        /// </summary>
        public static string render_opt_channel_width {
            get {
                return ResourceManager.GetString("render_opt_channel_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只渲染指定索引的事件层（需同时指定 --line）.
        /// </summary>
        public static string render_opt_layer {
            get {
                return ResourceManager.GetString("render_opt_layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只渲染指定索引的判定线（不指定则渲染全部）.
        /// </summary>
        public static string render_opt_line {
            get {
                return ResourceManager.GetString("render_opt_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通道值域最小半宽（绝对，默认：0.1）.
        /// </summary>
        public static string render_opt_min_range_half {
            get {
                return ResourceManager.GetString("render_opt_min_range_half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通道值域最小半宽比例（默认：0.05）.
        /// </summary>
        public static string render_opt_min_range_half_ratio {
            get {
                return ResourceManager.GetString("render_opt_min_range_half_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片输出文件夹路径。.
        /// </summary>
        public static string render_opt_output {
            get {
                return ResourceManager.GetString("render_opt_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每拍对应的像素高度（默认：100）.
        /// </summary>
        public static string render_opt_pixels_per_beat {
            get {
                return ResourceManager.GetString("render_opt_pixels_per_beat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通道值域填充比例（默认：0.1）.
        /// </summary>
        public static string render_opt_range_padding_ratio {
            get {
                return ResourceManager.GetString("render_opt_range_padding_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通道值域计算采样点数（默认：256）.
        /// </summary>
        public static string render_opt_range_samples {
            get {
                return ResourceManager.GetString("render_opt_range_samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每个事件的曲线采样点数（默认：64）.
        /// </summary>
        public static string render_opt_samples {
            get {
                return ResourceManager.GetString("render_opt_samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件段压缩容差（默认：0.05）.
        /// </summary>
        public static string render_opt_segment_tolerance {
            get {
                return ResourceManager.GetString("render_opt_segment_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有找到可渲染的事件层，请检查输入谱面或 --line / --layer 参数。.
        /// </summary>
        public static string render_warn_nothing {
            get {
                return ResourceManager.GetString("render_warn_nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您正在使用预发布版本，若发现问题，请及时反馈到 {0} ，感谢支持。.
        /// </summary>
        public static string warn_unstable_version {
            get {
                return ResourceManager.GetString("warn_unstable_version", resourceCulture);
            }
        }
    }
}
