//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaedePhi.Tool.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GuiLocalizationString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiLocalizationString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaedePhi.Tool.Localization.GuiLocalizationString", typeof(GuiLocalizationString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开源的自制谱工具集.
        /// </summary>
        public static string app_subtitle {
            get {
                return ResourceManager.GetString("app_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KaedePhi.
        /// </summary>
        public static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        public static string btn_back {
            get {
                return ResourceManager.GetString("btn_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回导入.
        /// </summary>
        public static string btn_back_to_import {
            get {
                return ResourceManager.GetString("btn_back_to_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回工具.
        /// </summary>
        public static string btn_back_to_tools {
            get {
                return ResourceManager.GetString("btn_back_to_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览.
        /// </summary>
        public static string btn_browse {
            get {
                return ResourceManager.GetString("btn_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出.
        /// </summary>
        public static string btn_export {
            get {
                return ResourceManager.GetString("btn_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出谱面.
        /// </summary>
        public static string btn_export_chart {
            get {
                return ResourceManager.GetString("btn_export_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string btn_ok {
            get {
                return ResourceManager.GetString("btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 恢复默认.
        /// </summary>
        public static string btn_reset_defaults {
            get {
                return ResourceManager.GetString("btn_reset_defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行工具.
        /// </summary>
        public static string btn_run_tool {
            get {
                return ResourceManager.GetString("btn_run_tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存设置.
        /// </summary>
        public static string btn_save_settings {
            get {
                return ResourceManager.GetString("btn_save_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string btn_settings {
            get {
                return ResourceManager.GetString("btn_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha事件切割精度.
        /// </summary>
        public static string convert_alpha_precision {
            get {
                return ResourceManager.GetString("convert_alpha_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha事件容差（百分比）.
        /// </summary>
        public static string convert_alpha_tolerance {
            get {
                return ResourceManager.GetString("convert_alpha_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通用选项.
        /// </summary>
        public static string convert_common_options {
            get {
                return ResourceManager.GetString("convert_common_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回退BPM.
        /// </summary>
        public static string convert_default_bpm {
            get {
                return ResourceManager.GetString("convert_default_bpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缓动截取切割后压缩.
        /// </summary>
        public static string convert_easing_cut_compress {
            get {
                return ResourceManager.GetString("convert_easing_cut_compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缓动截取切割精度.
        /// </summary>
        public static string convert_easing_cut_precision {
            get {
                return ResourceManager.GetString("convert_easing_cut_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缓动截取切割.
        /// </summary>
        public static string convert_easing_cut_section {
            get {
                return ResourceManager.GetString("convert_easing_cut_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缓动截取切割容差百分比.
        /// </summary>
        public static string convert_easing_cut_tolerance {
            get {
                return ResourceManager.GetString("convert_easing_cut_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持缓动切割精度.
        /// </summary>
        public static string convert_easing_precision {
            get {
                return ResourceManager.GetString("convert_easing_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过滤假音符（删除假音符）.
        /// </summary>
        public static string convert_filter_fake_notes {
            get {
                return ResourceManager.GetString("convert_filter_fake_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帧转事件持续拍长度（1 / x 拍）.
        /// </summary>
        public static string convert_frame_duration_beat {
            get {
                return ResourceManager.GetString("convert_frame_duration_beat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 判定线过滤.
        /// </summary>
        public static string convert_line_filter {
            get {
                return ResourceManager.GetString("convert_line_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合并层级经典模式.
        /// </summary>
        public static string convert_merge_classic {
            get {
                return ResourceManager.GetString("convert_merge_classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合并层级后压缩.
        /// </summary>
        public static string convert_merge_compress {
            get {
                return ResourceManager.GetString("convert_merge_compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合并层级精度.
        /// </summary>
        public static string convert_merge_precision {
            get {
                return ResourceManager.GetString("convert_merge_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多层级合并.
        /// </summary>
        public static string convert_merge_section {
            get {
                return ResourceManager.GetString("convert_merge_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合并层级容差百分比.
        /// </summary>
        public static string convert_merge_tolerance {
            get {
                return ResourceManager.GetString("convert_merge_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 负透明度段判定线抬高至屏幕外.
        /// </summary>
        public static string convert_negative_alpha_elevation {
            get {
                return ResourceManager.GetString("convert_negative_alpha_elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 负透明度抬高步长（归一化Y）.
        /// </summary>
        public static string convert_negative_alpha_step {
            get {
                return ResourceManager.GetString("convert_negative_alpha_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换选项.
        /// </summary>
        public static string convert_options_title {
            get {
                return ResourceManager.GetString("convert_options_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换到 PhiEdit 格式选项.
        /// </summary>
        public static string convert_pe_options {
            get {
                return ResourceManager.GetString("convert_pe_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换到 PhiChain 格式选项.
        /// </summary>
        public static string convert_phichain_options {
            get {
                return ResourceManager.GetString("convert_phichain_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换到 PhigrosV3 格式选项.
        /// </summary>
        public static string convert_phigros_options {
            get {
                return ResourceManager.GetString("convert_phigros_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除绑定UI的判定线.
        /// </summary>
        public static string convert_remove_attach_ui {
            get {
                return ResourceManager.GetString("convert_remove_attach_ui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除带有自定义纹理的判定线.
        /// </summary>
        public static string convert_remove_texture {
            get {
                return ResourceManager.GetString("convert_remove_texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换到 RePhiEdit 格式选项.
        /// </summary>
        public static string convert_rephiedit_options {
            get {
                return ResourceManager.GetString("convert_rephiedit_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 速度事件切割精度.
        /// </summary>
        public static string convert_speed_precision {
            get {
                return ResourceManager.GetString("convert_speed_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尾部拍填充量（1 / x 拍）.
        /// </summary>
        public static string convert_trailing_beat_padding {
            get {
                return ResourceManager.GetString("convert_trailing_beat_padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用经典模式解绑父线.
        /// </summary>
        public static string convert_unbind_classic {
            get {
                return ResourceManager.GetString("convert_unbind_classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解绑父线后压缩.
        /// </summary>
        public static string convert_unbind_compress {
            get {
                return ResourceManager.GetString("convert_unbind_compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解绑父线事件层合并容差（百分比）.
        /// </summary>
        public static string convert_unbind_merge_tolerance {
            get {
                return ResourceManager.GetString("convert_unbind_merge_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解绑非旋转子线.
        /// </summary>
        public static string convert_unbind_non_rotating {
            get {
                return ResourceManager.GetString("convert_unbind_non_rotating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解绑父线精度.
        /// </summary>
        public static string convert_unbind_precision {
            get {
                return ResourceManager.GetString("convert_unbind_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父子线解绑.
        /// </summary>
        public static string convert_unbind_section {
            get {
                return ResourceManager.GetString("convert_unbind_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解绑父线容差（百分比）.
        /// </summary>
        public static string convert_unbind_tolerance {
            get {
                return ResourceManager.GetString("convert_unbind_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出失败.
        /// </summary>
        public static string export_error_title {
            get {
                return ResourceManager.GetString("export_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式化输出（缩进）.
        /// </summary>
        public static string export_indented_output {
            get {
                return ResourceManager.GetString("export_indented_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出格式.
        /// </summary>
        public static string export_output_format {
            get {
                return ResourceManager.GetString("export_output_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出路径不能覆盖输入谱面文件。.
        /// </summary>
        public static string export_same_file_error {
            get {
                return ResourceManager.GetString("export_same_file_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流式写入.
        /// </summary>
        public static string export_stream_writing {
            get {
                return ResourceManager.GetString("export_stream_writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出成功.
        /// </summary>
        public static string export_success_title {
            get {
                return ResourceManager.GetString("export_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出谱面.
        /// </summary>
        public static string export_title {
            get {
                return ResourceManager.GetString("export_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有文件.
        /// </summary>
        public static string file_type_all {
            get {
                return ResourceManager.GetString("file_type_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON 文件.
        /// </summary>
        public static string file_type_json {
            get {
                return ResourceManager.GetString("file_type_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhiEditer 谱面.
        /// </summary>
        public static string file_type_pe_chart {
            get {
                return ResourceManager.GetString("file_type_pe_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhiChain JSON.
        /// </summary>
        public static string file_type_phichain_json {
            get {
                return ResourceManager.GetString("file_type_phichain_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhiFans JSON.
        /// </summary>
        public static string file_type_phifans_json {
            get {
                return ResourceManager.GetString("file_type_phifans_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phigros v3 JSON.
        /// </summary>
        public static string file_type_phigros_json {
            get {
                return ResourceManager.GetString("file_type_phigros_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RePhiEdit JSON.
        /// </summary>
        public static string file_type_rpe_json {
            get {
                return ResourceManager.GetString("file_type_rpe_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件:.
        /// </summary>
        public static string header_file {
            get {
                return ResourceManager.GetString("header_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式:.
        /// </summary>
        public static string header_format {
            get {
                return ResourceManager.GetString("header_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入谱面文件.
        /// </summary>
        public static string import_button {
            get {
                return ResourceManager.GetString("import_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入选项.
        /// </summary>
        public static string import_convert_options {
            get {
                return ResourceManager.GetString("import_convert_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 释放以加载谱面.
        /// </summary>
        public static string import_drop_active {
            get {
                return ResourceManager.GetString("import_drop_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 或将文件拖放到此处.
        /// </summary>
        public static string import_drop_hint {
            get {
                return ResourceManager.GetString("import_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择谱面文件.
        /// </summary>
        public static string import_file_picker_title {
            get {
                return ResourceManager.GetString("import_file_picker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载谱面....
        /// </summary>
        public static string import_loading {
            get {
                return ResourceManager.GetString("import_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认并加载.
        /// </summary>
        public static string import_options_confirm {
            get {
                return ResourceManager.GetString("import_options_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件:.
        /// </summary>
        public static string import_options_file {
            get {
                return ResourceManager.GetString("import_options_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到格式:.
        /// </summary>
        public static string import_options_format {
            get {
                return ResourceManager.GetString("import_options_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入选项.
        /// </summary>
        public static string import_options_title {
            get {
                return ResourceManager.GetString("import_options_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流式加载.
        /// </summary>
        public static string import_stream_loading {
            get {
                return ResourceManager.GetString("import_stream_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载失败.
        /// </summary>
        public static string load_error_title {
            get {
                return ResourceManager.GetString("load_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用程序启动中....
        /// </summary>
        public static string log_app_starting {
            get {
                return ResourceManager.GetString("log_app_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法访问文件选择器。.
        /// </summary>
        public static string log_cannot_access_picker {
            get {
                return ResourceManager.GetString("log_cannot_access_picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 谱面已加载，准备处理。.
        /// </summary>
        public static string log_chart_ready {
            get {
                return ResourceManager.GetString("log_chart_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出已取消。.
        /// </summary>
        public static string log_export_cancelled {
            get {
                return ResourceManager.GetString("log_export_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出完成。.
        /// </summary>
        public static string log_export_done {
            get {
                return ResourceManager.GetString("log_export_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出失败。.
        /// </summary>
        public static string log_export_failed {
            get {
                return ResourceManager.GetString("log_export_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在导出至: {0}，格式: {1}.
        /// </summary>
        public static string log_exporting_to {
            get {
                return ResourceManager.GetString("log_exporting_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择文件: {0}, 流式={1}.
        /// </summary>
        public static string log_file_selected {
            get {
                return ResourceManager.GetString("log_file_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载文件失败。.
        /// </summary>
        public static string log_load_failed {
            get {
                return ResourceManager.GetString("log_load_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已导航至导入页面。.
        /// </summary>
        public static string log_navigate_import {
            get {
                return ResourceManager.GetString("log_navigate_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在运行工具: {0}.
        /// </summary>
        public static string log_running_tool {
            get {
                return ResourceManager.GetString("log_running_tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用程序关闭，正在清除工作区。.
        /// </summary>
        public static string log_shutdown {
            get {
                return ResourceManager.GetString("log_shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在转换为中间格式....
        /// </summary>
        public static string log_step_converting {
            get {
                return ResourceManager.GetString("log_step_converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已检测到格式: {0}.
        /// </summary>
        public static string log_step_detected {
            get {
                return ResourceManager.GetString("log_step_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载文件....
        /// </summary>
        public static string log_step_loading {
            get {
                return ResourceManager.GetString("log_step_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具 &quot;{0}&quot; 已完成。您可以运行其它工具或导出。.
        /// </summary>
        public static string log_tool_completed {
            get {
                return ResourceManager.GetString("log_tool_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具执行失败。.
        /// </summary>
        public static string log_tool_failed {
            get {
                return ResourceManager.GetString("log_tool_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渲染输出: {0}.
        /// </summary>
        public static string log_tool_render_output {
            get {
                return ResourceManager.GetString("log_tool_render_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区已清除。.
        /// </summary>
        public static string log_workspace_cleared {
            get {
                return ResourceManager.GetString("log_workspace_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拍细分数.
        /// </summary>
        public static string option_beat_subdivisions {
            get {
                return ResourceManager.GetString("option_beat_subdivisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通道宽度.
        /// </summary>
        public static string option_channel_width {
            get {
                return ResourceManager.GetString("option_channel_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 经典模式.
        /// </summary>
        public static string option_classic_mode {
            get {
                return ResourceManager.GetString("option_classic_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用压缩.
        /// </summary>
        public static string option_disable_compress {
            get {
                return ResourceManager.GetString("option_disable_compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅在启用经典模式时可用.
        /// </summary>
        public static string option_disable_compress_hint {
            get {
                return ResourceManager.GetString("option_disable_compress_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全搜索长度阈值.
        /// </summary>
        public static string option_full_search_threshold {
            get {
                return ResourceManager.GetString("option_full_search_threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保留原事件偏置.
        /// </summary>
        public static string option_keep_original_penalty {
            get {
                return ResourceManager.GetString("option_keep_original_penalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长段回看窗口.
        /// </summary>
        public static string option_long_run_window {
            get {
                return ResourceManager.GetString("option_long_run_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小值域半宽.
        /// </summary>
        public static string option_min_value_range_half {
            get {
                return ResourceManager.GetString("option_min_value_range_half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小值域半宽比例.
        /// </summary>
        public static string option_min_value_range_half_ratio {
            get {
                return ResourceManager.GetString("option_min_value_range_half_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相位检测精度.
        /// </summary>
        public static string option_phase_epsilon {
            get {
                return ResourceManager.GetString("option_phase_epsilon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每拍像素.
        /// </summary>
        public static string option_pixels_per_beat {
            get {
                return ResourceManager.GetString("option_pixels_per_beat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精度.
        /// </summary>
        public static string option_precision {
            get {
                return ResourceManager.GetString("option_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 值域填充比例.
        /// </summary>
        public static string option_range_padding_ratio {
            get {
                return ResourceManager.GetString("option_range_padding_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 值域采样点数.
        /// </summary>
        public static string option_range_samples {
            get {
                return ResourceManager.GetString("option_range_samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片输出文件夹（默认为谱面同级目录下的 RenderLayer）.
        /// </summary>
        public static string option_render_output_dir {
            get {
                return ResourceManager.GetString("option_render_output_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出文件夹路径（不存在时自动创建）.
        /// </summary>
        public static string option_render_output_dir_hint {
            get {
                return ResourceManager.GetString("option_render_output_dir_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每事件采样数.
        /// </summary>
        public static string option_samples_per_event {
            get {
                return ResourceManager.GetString("option_samples_per_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 段分组容差.
        /// </summary>
        public static string option_segment_group_tolerance {
            get {
                return ResourceManager.GetString("option_segment_group_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 段惩罚.
        /// </summary>
        public static string option_segment_penalty {
            get {
                return ResourceManager.GetString("option_segment_penalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容差 (百分比).
        /// </summary>
        public static string option_tolerance {
            get {
                return ResourceManager.GetString("option_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父子线事件通道合并容差（百分比）.
        /// </summary>
        public static string option_unbind_merge_tolerance {
            get {
                return ResourceManager.GetString("option_unbind_merge_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string processing_error {
            get {
                return ResourceManager.GetString("processing_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志文件:.
        /// </summary>
        public static string processing_log_file {
            get {
                return ResourceManager.GetString("processing_log_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作已完成。.
        /// </summary>
        public static string processing_success {
            get {
                return ResourceManager.GetString("processing_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 处理谱面.
        /// </summary>
        public static string processing_title {
            get {
                return ResourceManager.GetString("processing_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择渲染输出文件夹.
        /// </summary>
        public static string render_output_dir_picker_title {
            get {
                return ResourceManager.GetString("render_output_dir_picker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式转换.
        /// </summary>
        public static string settings_convert {
            get {
                return ResourceManager.GetString("settings_convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件切割.
        /// </summary>
        public static string settings_cut {
            get {
                return ResourceManager.GetString("settings_cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件拟合.
        /// </summary>
        public static string settings_fit {
            get {
                return ResourceManager.GetString("settings_fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 层级合并.
        /// </summary>
        public static string settings_layermerge {
            get {
                return ResourceManager.GetString("settings_layermerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大日志文件数.
        /// </summary>
        public static string settings_max_log_files {
            get {
                return ResourceManager.GetString("settings_max_log_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 谱面渲染.
        /// </summary>
        public static string settings_render {
            get {
                return ResourceManager.GetString("settings_render", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已恢复默认设置。.
        /// </summary>
        public static string settings_reset {
            get {
                return ResourceManager.GetString("settings_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置保存失败，请检查权限或磁盘空间。.
        /// </summary>
        public static string settings_save_failed {
            get {
                return ResourceManager.GetString("settings_save_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置已保存。.
        /// </summary>
        public static string settings_saved {
            get {
                return ResourceManager.GetString("settings_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认设置.
        /// </summary>
        public static string settings_title {
            get {
                return ResourceManager.GetString("settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 判定线解绑.
        /// </summary>
        public static string settings_unbind {
            get {
                return ResourceManager.GetString("settings_unbind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法访问文件选择器。.
        /// </summary>
        public static string status_cannot_access_picker {
            get {
                return ResourceManager.GetString("status_cannot_access_picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误: {0}。详见日志: {1}.
        /// </summary>
        public static string status_error_with_log {
            get {
                return ResourceManager.GetString("status_error_with_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出已取消。.
        /// </summary>
        public static string status_export_cancelled {
            get {
                return ResourceManager.GetString("status_export_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已导出至: {0}.
        /// </summary>
        public static string status_exported_to {
            get {
                return ResourceManager.GetString("status_exported_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在导出....
        /// </summary>
        public static string status_exporting {
            get {
                return ResourceManager.GetString("status_exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已加载 {0} 条判定线。.
        /// </summary>
        public static string status_loaded_lines {
            get {
                return ResourceManager.GetString("status_loaded_lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在处理....
        /// </summary>
        public static string status_processing {
            get {
                return ResourceManager.GetString("status_processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具 &quot;{0}&quot; 已完成。您可以运行其它工具或导出。.
        /// </summary>
        public static string status_tool_completed {
            get {
                return ResourceManager.GetString("status_tool_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推断格式.
        /// </summary>
        public static string step_detecting {
            get {
                return ResourceManager.GetString("step_detecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换回原始格式.
        /// </summary>
        public static string step_from_kpc {
            get {
                return ResourceManager.GetString("step_from_kpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载文件.
        /// </summary>
        public static string step_loading {
            get {
                return ResourceManager.GetString("step_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用工具.
        /// </summary>
        public static string step_running_tool {
            get {
                return ResourceManager.GetString("step_running_tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出到工作区.
        /// </summary>
        public static string step_saving {
            get {
                return ResourceManager.GetString("step_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换为中间格式.
        /// </summary>
        public static string step_to_kpc {
            get {
                return ResourceManager.GetString("step_to_kpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将事件按等长段切割.
        /// </summary>
        public static string tool_cut_desc {
            get {
                return ResourceManager.GetString("tool_cut_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件切割.
        /// </summary>
        public static string tool_cut_name {
            get {
                return ResourceManager.GetString("tool_cut_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具运行失败.
        /// </summary>
        public static string tool_error_title {
            get {
                return ResourceManager.GetString("tool_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将线性事件拟合为缓动曲线.
        /// </summary>
        public static string tool_fit_desc {
            get {
                return ResourceManager.GetString("tool_fit_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件拟合.
        /// </summary>
        public static string tool_fit_name {
            get {
                return ResourceManager.GetString("tool_fit_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将多个事件层合并为单层.
        /// </summary>
        public static string tool_layermerge_desc {
            get {
                return ResourceManager.GetString("tool_layermerge_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 层级合并.
        /// </summary>
        public static string tool_layermerge_name {
            get {
                return ResourceManager.GetString("tool_layermerge_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具选项.
        /// </summary>
        public static string tool_options_title {
            get {
                return ResourceManager.GetString("tool_options_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将谱面事件层渲染为图片.
        /// </summary>
        public static string tool_render_desc {
            get {
                return ResourceManager.GetString("tool_render_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事件渲染.
        /// </summary>
        public static string tool_render_name {
            get {
                return ResourceManager.GetString("tool_render_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择工具.
        /// </summary>
        public static string tool_select_title {
            get {
                return ResourceManager.GetString("tool_select_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具运行成功.
        /// </summary>
        public static string tool_success_title {
            get {
                return ResourceManager.GetString("tool_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将子判定线从父线坐标系解绑为绝对坐标.
        /// </summary>
        public static string tool_unbind_desc {
            get {
                return ResourceManager.GetString("tool_unbind_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父子线解绑.
        /// </summary>
        public static string tool_unbind_name {
            get {
                return ResourceManager.GetString("tool_unbind_name", resourceCulture);
            }
        }
    }
}
